-- AUTO-GENERATED DRAFT from getblock JSON
-- Review and normalize into relational tables (see schema.sql)
CREATE TABLE IF NOT EXISTS blocks_flat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash TEXT,
    confirmations INTEGER,
    height INTEGER,
    version INTEGER,
    versionhex TEXT,
    merkleroot TEXT,
    time INTEGER,
    mediantime INTEGER,
    nonce INTEGER,
    bits TEXT,
    target TEXT,
    difficulty REAL,
    chainwork TEXT,
    ntx INTEGER,
    previousblockhash TEXT,
    nextblockhash TEXT,
    strippedsize INTEGER,
    size INTEGER,
    weight INTEGER,
    coinbase_tx_version INTEGER,
    coinbase_tx_locktime INTEGER,
    coinbase_tx_sequence INTEGER,
    coinbase_tx_coinbase TEXT,
    tx_item_txid TEXT,
    tx_item_hash TEXT,
    tx_item_version INTEGER,
    tx_item_size INTEGER,
    tx_item_vsize INTEGER,
    tx_item_weight INTEGER,
    tx_item_locktime INTEGER,
    tx_item_vin_item_coinbase TEXT,
    tx_item_vin_item_sequence INTEGER,
    tx_item_vout_item_value REAL,
    tx_item_vout_item_n INTEGER,
    tx_item_vout_item_scriptpubkey_asm TEXT,
    tx_item_vout_item_scriptpubkey_desc TEXT,
    tx_item_vout_item_scriptpubkey_hex TEXT,
    tx_item_vout_item_scriptpubkey_type TEXT,
    tx_item_hex TEXT
);
